// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type App struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Size *int   `json:"size,omitempty"`
}

type NewApp struct {
	Name string `json:"name"`
	Size *int   `json:"size,omitempty"`
}

type NewUser struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
